language: python
python:
  - "2.7"

# Short duration job, use the container/without sudo image as it boots faster
sudo: false
# Use the latest Travis images since they are more up to date than the stable release.
group: edge

cache:
  directories:
    - "~/.platformio"

env:
  global:
     - PLATFORMIO_CI_SRC=examples/DMXUSB_Simple
     - PLATFORMIO_CI_SRC=examples/DMXUSB_DmxSimple
     - PLATFORMIO_CI_SRC=examples/DMXUSB_FastLED
  matrix:
    fast_finish: true
    include:
     - env: BOARD=uno 
     - env: BOARD=megaatmega2560
     - env: BOARD=diecimilaatmega328
     - env: BOARD=leonardo
     - env: BOARD=micro
     - env: BOARD=nanoatmega328
     - env: BOARD=pro16MHzatmega328
     - env: BOARD=teensy20
     - env: BOARD=teensy20pp
     - env: BOARD=teensylc
     - env: BOARD=teensy30
     - env: BOARD=teensy31
     - env: BOARD=teensy35
     - env: BOARD=teensy36
     - env: BOARD=nodemcu
     - env: BOARD=nodemcuv2
     - env: BOARD=huzzah
  #   - env: BOARD=lenny # This is a PIC32 board. Travis doesn't have pic32-g++
     - env: BOARD=genuino101
     - env: BOARD=due
     - env: BOARD=dueUSB
     - env: BOARD=zero
     - env: BOARD=zeroUSB
     - env: BOARD=mzeroUSB
     - env: BOARD=mzeropro
     - env: BOARD=mzeroproUSB

before_install:
 - pip install -U platformio

install:
# Libraries from PlatformIO Library Registry:
# http://platformio.org/lib/show/1002/elapsedMillis
 - platformio lib -g install 1002
# http://platformio.org/lib/show/898/DmxSimple
 - platformio lib -g install 898
# http://platformio.org/lib/show/126/FastLED
 - platformio lib -g install 126

script:
 - platformio ci --lib="." --board=$BOARD
