language: python
python:
- "2.7"

# Short duration job, use the container/without sudo image as it boots faster
sudo: false
# Use the latest Travis images since they are more up to date than the stable release.
dist: trusty
group: edge

cache:
  directories:
  - "~/.platformio"

env:
  global:
  - PLATFORMIO_CI_SRC=examples/DMXUSB_Simple
  - PLATFORMIO_CI_SRC=examples/DMXUSB_DmxSimple
  - PLATFORMIO_CI_SRC=examples/DMXUSB_FastLED
  matrix:
  - BOARD=uno 
  - BOARD=megaatmega2560
  - BOARD=diecimilaatmega328
  - BOARD=leonardo
  - BOARD=micro
  - BOARD=nanoatmega328
  - BOARD=pro16MHzatmega328
  - BOARD=teensy20
  - BOARD=teensy20pp
  - BOARD=teensylc
  - BOARD=teensy30
  - BOARD=teensy31
  - BOARD=teensy35
  - BOARD=teensy36
  - BOARD=nodemcu
  - BOARD=nodemcuv2
  - BOARD=huzzah
 # - BOARD=lenny # This is a PIC32 board. Travis doesn't have pic32-g++
  - BOARD=genuino101
  - BOARD=due
  - BOARD=dueUSB
  - BOARD=zero
  - BOARD=zeroUSB
  - BOARD=mzeroUSB
  - BOARD=mzeropro
  - BOARD=mzeroproUSB

matrix:
  fast_finish: true

before_install:
- pip install -U platformio

install:
# Libraries from PlatformIO Library Registry:
# http://platformio.org/lib/show/1002/elapsedMillis
- platformio lib -g install 1002
# http://platformio.org/lib/show/898/DmxSimple
- platformio lib -g install 898
# http://platformio.org/lib/show/126/FastLED
- platformio lib -g install 126

script:
- platformio ci --lib="." --board=$BOARD
